meta:
  title:
  thumbnail:
  description:
  sns:
    - twitter
slide:
  loop: true
  sidebar: true
  targetBlank: true
  showIndex: true
  isVertical: false
  code:
    languages:
      - yaml
      - json
      - markdown
      - javascript
      - jsx
      - css
    plugins: []
    theme: default
  chart: false
  math: false
build:
  ssr: true
